### ISSUE TITLE
AE2 Interface blocking mode does not work with Packager

### ISSUE THREAD

**Issue by malakai97** [TheLMiffy1111/PackagedAuto#10]
When an AE2 Interface is pointing at a Packager, the Interface's blocking mode does not work. 

This makes it difficult if one wants to e.g. have the Packager create packages that are then moved to a suite of Unpackagers outside of the AE network, such as for task parallelization.

**Comment by TheLMiffy1111** [comment]
The only way to fix this issue is to make items already inputted into the packager extractable, which I consider to be a bad thing. Judging from your use case, the better solution id to make an in-game option to let packagers not put packages automatically back into the ME system, so that the packages can be moved to other places more easily, and I will certainly look into that.

**Comment by malakai97** [comment]
Thanks! I do think that would address my (and others') need. 

> The only way to fix this issue is to make items already inputted into the packager extractable

Are you sure about this? When I think of machines like the EIO alloy smelter or any Thermal Expansion machine, one cannot pull from the input slots, only the outputs. I realize this mod is not those mods so there could be other factors at play.

**Comment by malakai97** [comment]
This and #11 were both encountered in the course of trying to accomplish the same thing. If it's all the same to you, #11 is more important because it allows one to achieve the goal without creating AE2 patterns. Having ~this~ the functionality in this issue would still require one to create both a packagedauto recipe and an AE2 pattern for every craft.
