### ISSUE TITLE
Items imported through Unpackager Disappearing

### ISSUE THREAD

**Issue by Rithenar** [TheLMiffy1111/PackagedAuto#17]
I wanted to try crafted items things into my AE2 network using the same unpackager that carried the materials. The unpackager is acting as expected when exporting the materials and the  Automation Interface/Advanced Crafting Table setup work just fine. However, once the recipe completes the Automation Interface exports the crafted item to the Unpackager where it disappears.  I have checked all my storage, and I have enough room in my AE2 drives so I do not know what/where are these crafted items going...

I am running v. 1.0.2.9 and using it on Minecraft 1.12 on the PO3 Titan mode modpack

**Comment by Exaxxion** [comment]
Unpackagers can't accept items back into AE to complete the craft like ME Interfaces do. Automation Interfaces apparently don't check whether they can actually insert into a particular side and the items get voided because it thinks it moved the items.

I've had to just tell people not to make that mistake in Omnifactory. We added PackagedExtremeCrafting which allows you to forego using the horrid Automation Interfaces entirely which is really nice.
